### ISSUE TITLE
Update to new Shield namespace

### ISSUE THREAD

**Issue by jozefrebjak** [tattersoftware/codeigniter4-users#19]
@MGatner Please, update to new Shield namespace, I would like to use it with Permits.

**Comment by MGatner** [comment]
It's underway! See #18 where I got into it accidentally by trying to fix static analysis. There are still lots of changes happening to Shield (like removing `Authenticatable` today) so I'm waiting for the dust to settle. Probably this weekend I'll try for a found of updates.

**Comment by MGatner** [comment]
I think it is all working. I need to do one more review on that PR after today's updates to Shield, then I will get it released. 

If you need it opener feel free to switch to that PR's branch in the meantime.
